example:
  username: John
  password: password
  dburl: someURL
  jms:
    username: JMS Username
    password: JMS Password
    url: JMS URL

---
spring:
  profiles: de

example:
  jms:
    username: JSM Username, but in german